name: Git Clone, Unzip, Install, and Run

on:
  push:
    branches:
      - main  # Jalankan setiap ada push di branch 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Clone the target repository
    - name: Clone BUG repository
      run: |
        git clone https://github.com/Zet65/BUG.git

    # Step 2: Navigate into the BUG directory
    - name: Change directory to BUG
      run: cd BUG

    # Step 3: Unzip BUG.zip file inside the BUG folder
    - name: Unzip BUG.zip
      run: |
        sudo apt-get install unzip  # Install unzip tool if not already installed
        unzip BUG/BUG.zip -d ./BUG # Unzip BUG.zip in the BUG directory

    # Step 4: Install npm dependencies
    - name: Install npm dependencies
      run: |
        cd BUG
        npm install

    # Step 5: Start the npm application
    - name: Start the application
      run: |
        cd BUG
        npm start
